this["Perf"]&&void 0!==this["Perf"].enabled||(function(window){'use strict';/*
 Copyright (c) 2011, Yahoo! Inc.  All rights reserved.
 Copyright (c) 2012, Log-Normal, Inc.  All rights reserved.
 Copyright (c) 2013, SOASTA, Inc. All rights reserved.
 Copyright (c) 2013, Salesforce.com. All rights reserved.
 Copyrights licensed under the BSD License. See the accompanying LICENSE.txt file for terms.
*/
var e=(new Date).getTime(),n;
(function(){var d;window.parent!==window&&document.getElementById("boomr-if-as")&&"script"===document.getElementById("boomr-if-as").nodeName.toLowerCase()&&(window=window.parent,d=document.getElementById("boomr-if-as").src);var a=window.document,f=window.perfOptions||{},b={m:!1,W:!1,B:{page_ready:[],page_unload:[],dom_loaded:[],onLoad:[],visibility_changed:[],before_beacon:[],xhr_load:[],click:[],form_submit:[]},h:{},A:{},ta:function(g){var a;g||(g=window.event);g.target?a=g.target:g.srcElement&&
(a=g.srcElement);!a||"OBJECT"===a.nodeName.toUpperCase()&&"application/x-shockwave-flash"===a.type||(3===a.nodeType&&(a=a.parentNode),b.fireEvent("click",a))},ua:function(a){var c;a||(a=window.event);a.target?c=a.target:a.srcElement&&(c=a.srcElement);3===c.nodeType&&(c=c.parentNode);b.fireEvent("form_submit",c)},fireEvent:function(a,c){var p,d,f;if(!b.B.hasOwnProperty(a))return!1;f=b.B[a];for(p=0;p<f.length;p++)d=f[p],d[0].call(d[2],c,d[1]);return!0},bu:"",bt:"AUTO"};b.sd=window.location.hostname.replace(/.*?([^.]+\.[^.]+)\.?$/,
"$1").toLowerCase();b.uip="";b.sqs=!1;var c={N:"bu",Ba:"bt",F:"sd",Ea:"uip",ja:"sqs",n:null,g:e,url:d,fa:null,plugins:{},version:"1.0.5",window:window,b:{t:function(a,c){var b=[],d;if(!a||"object"!==typeof a)return a;void 0===c&&(c="\n\t");for(d in a)Object.prototype.hasOwnProperty.call(a,d)&&b.push(encodeURIComponent(d)+"="+encodeURIComponent(a[d]));return b.join(c)},H:function(c){if(!c)return null;c=" "+c+"=";var b,d;d=" "+a.cookie+";";return 0<=(b=d.indexOf(c))?(b+=c.length,d=d.substring(b,d.indexOf(";",
b))):null},setCookie:function(g,h,d){var f,l,m;if(!g||!b[c.F])return c.debug("No cookie name or site domain: "+g+"/"+b[c.F]),!1;h=c.b.t(h,"&");f=g+"="+h;l=[f,"path=/","domain="+b[c.F]];d&&(m=new Date,m.setTime(m.getTime()+1E3*d),m=m.toGMTString(),l.push("expires="+m));if(500>f.length){a.cookie=l.join("; ");g=c.b.H(g);if(h===g)return!0;c.warn("Saved cookie value doesn't match what we tried to set:\n"+h+"\n"+g)}else c.warn("Cookie too long: "+f.length+" "+f);return!1},T:function(a){var b,d,f,l=!1,m=
{};if(!a)return null;if("string"!==typeof a)return c.debug("TypeError: cookie is not a string: "+typeof a),null;a=a.split("&");b=0;for(d=a.length;b<d;b++)f=a[b].split("="),f[0]&&(f.push(""),m[decodeURIComponent(f[0])]=decodeURIComponent(f[1]),l=!0);return l?m:null},xa:function(a){return c.b.setCookie(a,{},-86400)},G:function(a){return b[c.ja]&&a?a.replace(/\?.*/,"?qs-redacted"):a},I:function(a,b){if(!a)return a;b&&(a=a.replace(/#.*/,""));return c.b.ia?a.replace(/\?([^#]*)/,function(a,b){return"?"+
(10<b.length?c.b.ia(b):b)}):a},wa:function(a,c,b,d){var f,m=0;if(!c||!c[b])return!1;for(f=0;f<d.length;f++)void 0!==c[b][d[f]]&&(a[d[f]]=c[b][d[f]],m++);return 0<m},addListener:function(a,c,b){a.addEventListener?a.addEventListener(c,b,!1):a.attachEvent("on"+c,b)},removeListener:function(a,c,b){a.removeEventListener?a.removeEventListener(c,b,!1):a.detachEvent("on"+c,b)},aa:function(a,b,d){var f,l,m=0;for(f in b)if(b.hasOwnProperty(f))if("[object Array]"===Object.prototype.toString.call(b[f]))for(l=
0;l<b[f].length;++l)m+=c.b.aa(a,b[f][l],f+"["+l+"]");else++m,a.push(encodeURIComponent(d?d+"["+f+"]":f)+"="+(void 0===b[f]||null===b[f]?"":encodeURIComponent(b[f])));return m},$:function(a){var f=document.createElement("iframe"),d=document.createElement("form"),k=document.createElement("input");f.name="boomerang_post";f.style.display=d.style.display="none";d.method="POST";d.action=b[c.N];d.target=f.name;k.name="data";window.JSON?(d.enctype="text/plain",k.value=JSON.stringify(b.h)):(d.enctype="application/x-www-form-urlencoded",
k.value=a);document.body.appendChild(f);d.appendChild(k);document.body.appendChild(d);c.b.addListener(f,"load",function(){document.body.removeChild(d);document.body.removeChild(f)});d.submit()}},l:function(g){var d,f,k=["bu","bt","sd","uip","sqs"];g||(g={});for(d=0;d<k.length;d++)void 0!==g[k[d]]&&(b[k[d]]=g[k[d]]);void 0!==g.log&&(c.log=g.log);c.log||(c.log=function(){});for(f in c.plugins)c.plugins.hasOwnProperty(f)&&(g[f]&&g[f].hasOwnProperty("enabled")&&!1===g[f].enabled?b.A[f]=1:(b.A[f]&&delete b.A[f],
"function"===typeof c.plugins[f].l&&c.plugins[f].l(g)));if(b.W)return c;b.m||void 0!==g.Q&&!1===g.Q||(a.readyState&&"complete"===a.readyState?c.setImmediate(c.D,null,null,c):window.onpagehide||null===window.onpagehide?c.b.addListener(window,"pageshow",c.D):c.b.addListener(window,"load",c.D));c.b.addListener(window,"DOMContentLoaded",function(){b.fireEvent("dom_loaded")});(function(){var g,f;g=function(){b.fireEvent("visibility_changed")};a.webkitVisibilityState?c.b.addListener(a,"webkitvisibilitychange",
g):a.msVisibilityState?c.b.addListener(a,"msvisibilitychange",g):a.visibilityState&&c.b.addListener(a,"visibilitychange",g);c.b.addListener(a,"mouseup",b.ta);g=a.getElementsByTagName("form");for(f=0;f<g.length;f++)c.b.addListener(g[f],"submit",b.ua);window.onpagehide||null===window.onpagehide||c.b.addListener(window,"unload",function(){delete c.window})})();b.W=!0;return c},D:function(a){a||(a=window.event);a||(a={name:"load"});if(b.m)return c;b.fireEvent("page_ready",a);b.m=!0;return c},setImmediate:function(a,
b,c,f){function d(){a.call(f||null,b,c||{});d=null}window.setImmediate?window.setImmediate(d):window.msSetImmediate?window.msSetImmediate(d):window.webkitSetImmediate?window.webkitSetImmediate(d):window.mozSetImmediate?window.mozSetImmediate(d):setTimeout(d,10)},subscribe:function(a,f,d,k){var l,m,u;if(!b.B.hasOwnProperty(a))return c;u=b.B[a];for(l=0;l<u.length;l++)if(m=u[l],m[0]===f&&m[1]===d&&m[2]===k)return c;u.push([f,d||{},k||null]);"page_ready"===a&&b.m&&c.setImmediate(f,null,d,k);"page_unload"===
a&&(a=function(a){f&&f.call(k,a||window.event,d)},window.onpagehide||null===window.onpagehide?c.b.addListener(window,"pagehide",a):c.b.addListener(window,"unload",a),c.b.addListener(window,"beforeunload",a));return c},d:function(a,f){if("string"===typeof a)b.h[a]=f;else if("object"===typeof a)for(var d in a)a.hasOwnProperty(d)&&(b.h[d]=a[d]);return c},ba:function(a){var f,d;if(!arguments.length)return c;d=1===arguments.length&&"[object Array]"===Object.prototype.toString.apply(a)?a:arguments;for(f=
0;f<d.length;f++)b.h.hasOwnProperty(d[f])&&delete b.h[d[f]];return c},V:function(){return b.h},ra:function(a){return b.h[a]},removeStats:function(){b.h={};c.plugins.c.la();return c},requestStart:function(a){var b=(new Date).getTime();c.plugins.c.i("xhr_"+a,b);return{loaded:function(){c.responseEnd(a,b)}}},responseEnd:function(a,f){c.plugins.c.i("xhr_"+a,f);b.fireEvent("xhr_load",{name:"xhr_"+a})},sendBeacon:function(){var f,d;c.debug("Checking if we can send beacon");for(f in c.plugins)if(c.plugins.hasOwnProperty(f)&&
!b.A[f]&&!c.plugins[f].C())return n.debug("Plugin "+f+" is not complete, deferring beacon send"),c;b.h.v=c.version;b.h.u=c.b.G(a.URL.replace(/#.*/,""));b.fireEvent("before_beacon",b.h);if(!b.bu)return c;d=[];if(!c.b.aa(d,b.h))return c;d=d.join("&");"POST"===b.bt?c.b.$(d):(f=b.bu+(-1<b.bu.indexOf("?")?"&":"?")+d,2E3<f.length&&"AUTO"===b.bt?c.b.$(d):(c.debug("Sending url: "+f.replace(/&/g,"\n\t")),d=new Image,d.src=f));return c}};c.n="number"===typeof f.BOOMR_lstart?f.BOOMR_lstart:c.window.perfOptions&&
"number"===typeof c.window.perfOptions.BOOMR_lstart?c.window.perfOptions.BOOMR_lstart:0;delete f.BOOMR_lstart;(function(){function a(b){return function(a,f){c.log(a,b,"boomerang"+(f?"."+f:""));return c}}window.YAHOO&&window.YAHOO.widget&&window.YAHOO.widget.Logger?c.log=window.YAHOO.log:window.Y&&window.Y.log?c.log=window.Y.log:"object"===typeof window.console&&void 0!==window.console.log&&(c.log=function(a,b,c){window.console.log(c+": ["+b+"] "+a)});c.debug=a("debug");c.info=a("info");c.warn=a("warn");
c.error=a("error")})();n=c})();(function(){var d=window.document;n=n||{};n.plugins=n.plugins||{};var a={Z:!1,m:!1,Ha:!1,complete:!1,a:{},cookie:"RT",ma:1800,za:!1,navigationType:0,redirectCount:0,navigationStart:void 0,responseStart:void 0,e:void 0,da:Math.floor(4294967296*Math.random()).toString(36),p:void 0,ea:0,g:void 0,q:void 0,o:null,w:null,L:function(b,c){var f,d;if(!a.cookie)return a;f=n.b.T(n.b.H(a.cookie))||{};if("object"===typeof b)for(d in b)if(b.hasOwnProperty(d))if(void 0===b[d])f.hasOwnProperty(d)&&delete f[d];else{if("nu"===
d||"r"===d)b[d]=n.b.I(b[d],!0);f[d]=b[d]}d=(new Date).getTime();c&&(f[c]=d);n.debug("Setting cookie (timer="+c+")\n"+n.b.t(f),"rt");if(!n.b.setCookie(a.cookie,f,a.ma))return n.error("cannot set start cookie","rt"),a;f=(new Date).getTime();50<f-d&&(n.b.xa(a.cookie),n.error("took more than 50ms to set cookie... aborting: "+d+" -> "+f,"rt"));return a},X:function(){var b,c=n.b.T(n.b.H(a.cookie));c&&(c.s=Math.max(+c.ul||0,+c.cl||0),n.debug("Read from cookie "+n.b.t(c),"rt"),c.s&&(c.r||c.nu)&&(a.o=c.r,
b=n.b.I(d.URL,!0),n.debug(a.o+" =?= "+a.w,"rt"),n.debug(c.s+" <? "+(+c.cl+15),"rt"),n.debug(c.nu+" =?= "+b,"rt"),!a.za||c.nu&&c.nu===b&&c.s<+c.cl+15||c.s===+c.ul&&a.o===a.w?(a.g=c.s,+c.hd>c.s&&(a.q=parseInt(c.hd,10))):a.g=a.q=void 0),a.L({s:void 0,r:void 0,nu:void 0,ul:void 0,cl:void 0,hd:void 0}))},oa:function(){n.g&&(n.plugins.c.i("boomerang",n.g),n.plugins.c.f("boomerang",n.fa),n.plugins.c.f("boomr_fb",n.g),n.n&&(n.plugins.c.f("boomr_ld",n.n),n.plugins.c.setTimer("boomr_lat",n.g-n.n,n.n)));if(window.performance&&
window.performance.getEntriesByName){var a,c,f={"rt.bmr.":n.url},d;for(d in f)if(f.hasOwnProperty(d)&&f[d]&&(a=window.performance.getEntriesByName(f[d]))&&0!==a.length)for(c in a=a[0],a)a.hasOwnProperty(c)&&c.match(/(Start|End)$/)&&0<a[c]&&n.d(d+c.replace(/^(...).*(St|En).*$/,"$1$2"),a[c])}},ka:function(){if(!(d.webkitVisibilityState&&"prerender"===d.webkitVisibilityState||d.msVisibilityState&&3===d.msVisibilityState))return!1;n.plugins.c.i("t_load",a.navigationStart);n.plugins.c.f("t_load");n.plugins.c.i("t_prerender",
a.navigationStart);n.plugins.c.i("t_postrender");n.subscribe("visibility_changed",n.plugins.c.k,"visible",n.plugins.c);return!0},sa:function(){var b,c;a.navigationStart||((b=window.performance||window.msPerformance||window.webkitPerformance||window.mozPerformance)&&b.navigation&&(a.navigationType=b.navigation.type,a.redirectCount=b.navigation.redirectCount),b&&b.timing?a.e=b.timing:window.chrome&&window.chrome.csi&&window.chrome.csi().startE?(a.e={navigationStart:window.chrome.csi().startE},c="csi"):
window.gtbExternal&&window.gtbExternal.startE()&&(a.e={navigationStart:window.gtbExternal.startE()},c="gtb"),a.e?(n.d("rt.start",c||"navigation"),a.navigationStart=a.e.navigationStart||a.e.fetchStart||void 0,a.responseStart=a.e.responseStart||void 0,navigator.userAgent.match(/Firefox\/[78]\./)&&(a.navigationStart=a.e.unloadEventStart||a.e.fetchStart||void 0)):n.warn("This browser doesn't support the WebTiming API","rt"))},pa:function(){a.e&&void 0!==a.e.fetchStart&&(n.plugins.c.setTimer("t_dns",a.e.domainLookupEnd-
a.e.domainLookupStart,a.e.domainLookupStart),n.plugins.c.setTimer("t_tcp",a.e.connectEnd-a.e.connectStart,a.e.connectStart),n.d("nt_nav_type",a.navigationType),n.d("nt_red_cnt",a.redirectCount))},va:function(b){n.debug("Unload called with "+n.b.t(b),"rt");a.L({r:d.URL},"beforeunload"===b.type?"ul":"hd")},P:function(b,c,f,d){if(f){for(n.debug(b+" called with "+f.nodeName,"rt");f&&f.nodeName.toUpperCase()!==c;)f=f.parentNode;f&&f.nodeName.toUpperCase()===c&&(n.debug("passing through","rt"),a.L({nu:d(f)},
"cl"))}},onclick:function(b){a.P("Click","A",b,function(a){return a.href})},onsubmit:function(b){a.P("Submit","FORM",b,function(a){a=a.action||d.URL;return a.match(/\?/)?a:a+"?"})},na:function(){n.plugins.c.f("t_domloaded")},onLoad:function(){n.plugins.c.f("t_onLoad")}},f=n.plugins.c={l:function(b){n.debug("init RT","rt");window!==n.window&&(window=n.window,d=window.document);n.b.wa(a,b,"RT",["cookie","cookie_exp","strict_referrer"]);a.o=a.w=n.b.I(d.referrer,!0);a.X();a.oa();if(a.Z)return f;a.complete=
!1;a.a={};n.subscribe("page_ready",f.k,"load",f);n.subscribe("dom_loaded",a.na,null,a);n.subscribe("page_unload",a.va,null,a);n.subscribe("click",a.onclick,null,a);n.subscribe("form_submit",a.onsubmit,null,a);n.subscribe("onLoad",a.onLoad,null,a);a.p||(a.p=n.n||n.g);a.Z=!0;return f},i:function(b,c){b&&("t_page"===b&&f.f("t_resp",c),a.a[b]={start:"number"===typeof c?c:(new Date).getTime()});return f},f:function(b,c){b&&(a.a[b]=a.a[b]||{},void 0===a.a[b].end&&(a.a[b].end="number"===typeof c?c:(new Date).getTime()));
return f},setTimer:function(b,c,d){b&&(a.a[b]={j:c,start:d});return f},Aa:function(b,c){b&&(a.a[c]=a.a[b],a.a[b]={})},la:function(){a.a={};return f},M:function(){if(a.a){var b,c;for(c in a.a)a.a.hasOwnProperty(c)&&(b=a.a[c],b.end&&b.start&&("number"!==typeof b.j&&(b.j=b.end-b.start),n.d(c,b.j)))}},U:function(){return a.a},startTransaction:function(a){return n.plugins.c.i("txn_"+a,(new Date).getTime())},endTransaction:function(a){return n.plugins.c.f("txn_"+a,(new Date).getTime())},qa:function(){return a.da},
S:function(){return a.p},isOnLoadFired:function(){return a.m},setServerTime:function(a,c){f.i("t_server",a).f("t_server",a+c)},k:function(b,c){n.debug("Called done with "+n.b.t(b)+", "+c,"rt");var d,h=(new Date).getTime(),p=0,k;a.complete=!1;a.X();a.sa();if(a.ka())return f;if(a.responseStart)if(f.f("t_resp",a.responseStart),a.a.t_load)f.setTimer("t_page",a.a.t_load.end-a.responseStart,a.responseStart);else{var l=h-a.responseStart;0<l&&f.setTimer("t_page",l,a.responseStart)}else a.a.hasOwnProperty("t_page")?
f.f("t_page"):a.q&&(f.f("t_resp",a.q),f.setTimer("t_page",h-a.q,a.q));a.a.hasOwnProperty("t_postrender")&&(f.f("t_postrender"),f.f("t_prerender"));a.navigationStart?d=a.navigationStart:a.g&&2!==a.navigationType?(d=a.g,n.d("rt.start","cookie")):(n.d("rt.start","none"),d=void 0);d&&a.p>d&&(a.p=n.n||n.g,a.ea=0);n.debug("Got start time: "+d,"rt");f.f("t_done",h);a.a.hasOwnProperty("t_server")&&(f.f("req_lat",a.a.t_server.start),a.e&&a.e.responseEnd&&(l=a.e.responseEnd-a.a.t_server.end,0<=l?f.setTimer("resp_lat",
l,a.a.t_server.end):n.warn("negative resp_lat: "+a.a.t_server.end+" - "+a.e.responseEnd)));n.ba("req_lat","resp_lat","t_server","t_done","t_page","t_resp","r","r2","rt.tstart","rt.bstart","rt.end","rt.ss","rt.sl","rt.lt","t_postrender","t_prerender","t_load");n.d("rt.tstart",d);n.d("rt.bstart",n.g);n.d("rt.end",a.a.t_done.end);a.pa();a.a.t_configfb&&("t_configfb"in a.a&&"number"!==typeof a.a.t_configfb.start||isNaN(a.a.t_configfb.start))&&("t_configjs"in a.a&&"number"===typeof a.a.t_configjs.start?
a.a.t_configfb.start=a.a.t_configjs.start:delete a.a.t_configfb);for(k in a.a)a.a.hasOwnProperty(k)&&(h=a.a[k],"number"!==typeof h.j&&("number"!==typeof h.start&&(h.start=d),h.j=h.end-h.start),isNaN(h.j)?delete h.j:(n.d(k,h.j),p++,delete a.a[k]));p&&(n.d("r",n.b.G(a.o)),a.w!==a.o&&n.d("r2",n.b.G(a.w)));n.d({"rt.sid":a.da,"rt.ss":a.p,"rt.sl":a.ea});a.complete=!0;n.sendBeacon();a.m=!0;return f},C:function(){return a.complete}}})();(function(){n=n||{};n.plugins=n.plugins||{};var d={complete:!1,k:function(){if(!d.complete){var a=n.window,b=a.performance,c=a.console,g=a.document,h="[object Opera]"==={}.toString.call(a.opera)?g.querySelectorAll:g.getElementsByTagName,a=void 0===h.call?function(a){return h(a)}:h,c=b&&b.memory?b.memory:c&&c.memory?c.memory:null;b&&b.getEntries&&b.getEntries().length&&n.d("dom.res",b.getEntries().length);c&&n.d({"mem.total":c.totalJSHeapSize,"mem.used":c.usedJSHeapSize});n.d({"dom.ln":a.call(g,"*").length,
"dom.sz":a.call(g,"html")[0].innerHTML.length,"dom.img":a.call(g,"img").length,"dom.script":a.call(g,"script").length});d.complete=!0;n.sendBeacon()}}},a=n.plugins.Ca={l:function(){n.subscribe("page_ready",d.k,null,d);return a},C:function(){return d.complete}}})();var q;"object"===typeof navigator&&(q=navigator.connection||navigator.mozConnection||navigator.webkitConnection||navigator.msConnection);q&&(n.d("mob.ct",q.type),n.d("mob.bw",q.Fa),n.d("mob.mt",q.Ga));(function(){n=n||{};n.plugins=n.plugins||{};var d={complete:!1,k:function(){if(!d.complete){var a=n.window.performance,b,c;n.ba("rtrestiming");if(a&&"function"===typeof a.getEntriesByType&&(a=a.getEntriesByType("resource"))){n.info("Client supports Resource Timing API","rtrestiming");c={};var g=document.createElement("A"),h;c.rtrestiming=Array(a.length);for(b=0;b<a.length;++b)g.href=a[b].name,h=c.rtrestiming[b]={name:g.host==window.location.host?g.pathname+g.search:a[b].name},0<a[b].responseEnd&&
(h.rt_total=Math.round(a[b].responseEnd-a[b].startTime),a[b].responseStart&&(h.rt_transfer=Math.round(a[b].responseEnd-a[b].responseStart))),a[b].domainLookupEnd&&a[b].domainLookupStart&&(h.rt_dns=Math.round(a[b].domainLookupEnd-a[b].domainLookupStart)),a[b].connectEnd&&a[b].connectStart&&(h.rt_tcp=Math.round(a[b].connectEnd-a[b].connectStart)),a[b].responseStart&&(h.rt_ttfb=Math.round(a[b].responseStart-a[b].startTime)),a[b].redirectEnd&&a[b].redirectStart&&(h.rt_red=Math.round(a[b].redirectEnd-a[b].redirectStart));
n.d(c)}d.complete=!0;n.sendBeacon()}}},a=n.plugins.O={l:function(){n.subscribe("page_ready",d.k,null,d);return a},C:function(){return d.complete},ga:"rtrestiming"}})();(function(){n=n||{};n.plugins=n.plugins||{};var d={R:n.window.document,ca:"script",complete:!1,J:!1,K:void 0,k:function(){d.complete||(d.complete=!0,d.J=!1,n.sendBeacon())},ya:function(){var a=d.R.getElementsByTagName(d.ca)[0],b=d.R.createElement(d.ca);d.K=(new Date).getTime();b.src=n.window.BOOMR_cURL;a.parentNode.insertBefore(b,a)}},a=n.plugins.ha={l:function(){if(d.complete)return a;if(d.J)return setTimeout(d.k,10),n.d("t_cjs",(new Date).getTime()-d.K),r.BOOMR_configt&&(n.d("t_cfb",r.BOOMR_configt-
d.K),delete r.BOOMR_configt),a;d.J=!0;n.subscribe("page_ready",d.ya,null,null);return a},C:function(){return d.complete}}})();n.fa=(new Date).getTime();var t={DEBUG:{name:"DEBUG",value:1},INTERNAL:{name:"INTERNAL",value:2},PRODUCTION:{name:"PRODUCTION",value:3},DISABLED:{name:"DISABLED",value:4}},v={PAGE_START_MARK:"PageStart",PERF_PAYLOAD_PARAM:"bulkPerf",MARK_NAME:"mark",MEASURE_NAME:"measure",MARK_START_TIME:"st",MARK_LAST_TIME:"lt",PAGE_NAME:"pn",ELAPSED_TIME:"et",REFERENCE_TIME:"rt",Perf_LOAD_DONE:"loadDone",STATS:{NAME:"stat",SERVER_ELAPSED:"internal_serverelapsed",DB_TOTAL_TIME:"internal_serverdbtotaltime",DB_CALLS:"internal_serverdbcalls",
DB_FETCHES:"internal_serverdbfetches"}};window.PerfConstants=v;window.PerfLogLevel=t;var r=window.perfOptions;r||(r={});var w={log:null,Ia:!0,ha:{enabled:!1},Da:{enabled:!!r.restiming},Q:!1};w[n.N]=r.bURL;n.l(w);r.pageStartTime&&n.plugins.c.i("t_page",r.pageStartTime);var x=null;function y(d){"string"===typeof d&&(d=t[d]);return d||t.INTERNAL}function z(d,a){n.plugins.c.Aa(d,a);return A}
var A={currentLogLevel:y(r.logLevel),mark:function(d,a){A.currentLogLevel.value<=y(a).value&&n.plugins.c.i(d);return A},endMark:function(d,a){A.currentLogLevel.value<=y(a).value&&n.plugins.c.f(d);return A},updateMarkName:z,setTimer:function(d,a,f){A.currentLogLevel.value<=y(f).value&&(0<=a?n.plugins.c.setTimer(d,a):n.plugins.c.f(d));return A},setServerTime:function(d,a){n.plugins.c.setServerTime(d,a);return A},measureToJson:function(d){return window.JSON?JSON.stringify(d):"{"+v.MEASURE_NAME+':"'+
d[v.MEASURE_NAME]+'",'+v.MARK_NAME+':"'+d[v.MARK_NAME]+'",'+v.ELAPSED_TIME+":"+d[v.ELAPSED_TIME]+","+v.REFERENCE_TIME+":"+d[v.REFERENCE_TIME]+"}"},toJson:function(d){n.plugins.c.M();var a=n.plugins.c.U(),f=n.plugins.c.S(),b=['{sessionID:"',n.plugins.c.qa(),'",st:',f,',pn:"',window.document.URL,'",uid:"',Math.round(1E15*Math.random()).toString(),'",'],c=[],g=[],h,p,k=n.V(),l;for(h in k)"r"!=h&&"r2"!=h&&"t_other"!=h&&k.hasOwnProperty(h)&&!isNaN(k[h])&&(d&&c.push('"'+h+'":'+k[h]),p={},p[v.MEASURE_NAME]=
p[v.MARK_NAME]=h,p[v.ELAPSED_TIME]=k[h],l=a[h],p[v.REFERENCE_TIME]=l&&l.start?l.start:f,g.push(A.measureToJson(p)));d&&b.push("marks:{",c.join(","),"},");k.hasOwnProperty(n.plugins.O.ga)&&window.JSON&&b.push("restiming:",JSON.stringify(k[n.plugins.O.ga]),",");b.push("measures:[",g.join(","),"]}");return b.join("")},toPostVar:function(){return v.PERF_PAYLOAD_PARAM+"="+A.toJson().replace(/&/g,"__^__")},getMeasures:function(){n.plugins.c.M();var d=n.plugins.c.U(),a=n.plugins.c.S(),f=[],b=n.V(),c,g;for(c in b)"r"!=
c&&"r2"!=c&&"t_other"!=c&&b.hasOwnProperty(c)&&!isNaN(b[c])&&(g={},g[v.MEASURE_NAME]=c,g[v.MARK_NAME]=c,g[v.ELAPSED_TIME]=b[c],g[v.REFERENCE_TIME]=d[c]?d[c].start:a,f.push(g));return f},getBeaconData:function(){return x},setBeaconData:function(d){x=d},clearBeaconData:function(){x=null},removeStats:n.removeStats,subscribe:n.subscribe,stat:function(d,a){n.d("st_"+d,a);return A},getStat:function(d){n.plugins.c.M();return d?n.ra(d):-1},onLoad:n.D,startTransaction:function(d){n.plugins.c.startTransaction(d);
return A},endTransaction:function(d){n.plugins.c.endTransaction(d);return A},updateTransaction:z,isOnLoadFired:n.plugins.c.isOnLoadFired,util:{setCookie:function(d,a,f,b){document.cookie=d+"="+escape(a+"")+(f?"; expires="+f.toGMTString():"")+(b?"; path="+b:"; path=/")}},enabled:!0};window.Perf=A;window.PerfLogLevel=t;window.PerfConstants=v;})(this);
//# sourceMappingURL=perf.js.map
